[package]
name = "gallery"
version = "0.1.0"
authors = ["Balthild <ibalthild@gmail.com>"]
edition = "2021"

[dependencies]
async-channel = "2.3.1"
iced = { version = "0.13.1", features = ["highlighter"] }
saphyr = "0.0.4"

[dependencies.native-dialog]
path = "../.."
features = ["async"]
